config/routes.rb
App001::Application.routes.draw do
  resources :evaluations

  root to: "home#index"
  
  get "home/index"
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :experiences do
    collection do 
      get :random
    end
  end
  resources :subcategories
  resources :categories
  resources :password_resets
  resources :users
  resources :sessions

end

app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
  belongs_to :experience
  belongs_to :user
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  before_action :set_evaluation, only: [:show, :edit, :update, :destroy]

  # GET /evaluations
  # GET /evaluations.json
  def index
    @evaluations = Evaluation.all
  end

  # GET /evaluations/1
  # GET /evaluations/1.json
  def show
  end

  # GET /evaluations/new
  def new
    @evaluation = Evaluation.new
  end

  # GET /evaluations/1/edit
  def edit
  end

  # POST /evaluations
  # POST /evaluations.json
  def create
    @evaluation = Evaluation.new(evaluation_params)

    respond_to do |format|
      if @evaluation.save
        format.html { redirect_to @evaluation, notice: 'Evaluation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @evaluation }
      else
        format.html { render action: 'new' }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluations/1
  # PATCH/PUT /evaluations/1.json
  def update
    respond_to do |format|
      if @evaluation.update(evaluation_params)
        format.html { redirect_to @evaluation, notice: 'Evaluation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluations/1
  # DELETE /evaluations/1.json
  def destroy
    @evaluation.destroy
    respond_to do |format|
      format.html { redirect_to evaluations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluation
      @evaluation = Evaluation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evaluation_params
      params.require(:evaluation).permit(:experience_id, :user_id, :grade)
    end
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/views/evaluations/_form.html.haml
= simple_form_for(@evaluation) do |f|
  = f.error_notification

  .form-inputs
    = f.association :experience
    = f.association :user
    = f.input :grade

  .form-actions
    = f.button :submit

app/views/evaluations/edit.html.haml
%h1 Editing evaluation

= render 'form'

= link_to 'Show', @evaluation
\|
= link_to 'Back', evaluations_path

app/views/evaluations/index.html.haml
%h1 Listing evaluations

%table
  %tr
    %th Experience
    %th User
    %th Grade
    %th
    %th
    %th

  - @evaluations.each do |evaluation|
    %tr
      %td= evaluation.experience
      %td= evaluation.user
      %td= evaluation.grade
      %td= link_to 'Show', evaluation
      %td= link_to 'Edit', edit_evaluation_path(evaluation)
      %td= link_to 'Destroy', evaluation, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Evaluation', new_evaluation_path

app/views/evaluations/new.html.haml
%h1 New evaluation

= render 'form'

= link_to 'Back', evaluations_path

app/views/evaluations/show.html.haml
%p#notice= notice

%p
  %b Experience:
  = @evaluation.experience
%p
  %b User:
  = @evaluation.user
%p
  %b Grade:
  = @evaluation.grade

= link_to 'Edit', edit_evaluation_path(@evaluation)
\|
= link_to 'Back', evaluations_path