config/routes.rb
App001::Application.routes.draw do
  resources :evaluations

  root to: "home#index"
  
  get "home/index"
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :experiences do
    collection do 
      get :random
    end
  end
  resources :subcategories
  resources :categories
  resources :password_resets
  resources :users
  resources :sessions

end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  belongs_to :category
  has_many :experiences, dependent: :destroy

  def to_s
    name
  end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :load_subcategory, only: :create
  load_and_authorize_resource

  # GET /subcategories
  # GET /subcategories.json
  def index
    @subcategories = Subcategory.all
  end

  # GET /subcategories/1
  # GET /subcategories/1.json
  def show
  end

  # GET /subcategories/new
  def new
    @subcategory = Subcategory.new
  end

  # GET /subcategories/1/edit
  def edit
  end

  # POST /subcategories
  # POST /subcategories.json
  def create
    @subcategory = Subcategory.new(subcategory_params)

    respond_to do |format|
      if @subcategory.save
        format.html { redirect_to @subcategory, notice: 'Subcategory was successfully created.' }
        format.json { render action: 'show', status: :created, location: @subcategory }
      else
        format.html { render action: 'new' }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subcategories/1
  # PATCH/PUT /subcategories/1.json
  def update
    respond_to do |format|
      if @subcategory.update(subcategory_params)
        format.html { redirect_to @subcategory, notice: 'Subcategory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcategories/1
  # DELETE /subcategories/1.json
  def destroy
    @subcategory.destroy
    respond_to do |format|
      format.html { redirect_to subcategories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def load_subcategory
      @subcategory = Subcategory.new(subcategory_params)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subcategory_params
      params.require(:subcategory).permit(:category_id, :name)
    end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/helpers/subcategory_helper.rb
module SubcategoryHelper
end

app/views/subcategories/_form.html.haml
= simple_form_for(@subcategory) do |f|
  = f.error_notification

  .form-inputs
    = f.association :category
    = f.input :name

  .form-actions
    = f.button :submit, class: 'pull-right btn btn-primary'
    .clearfix

app/views/subcategories/edit.html.haml
.row
  .col-sm-8.col-sm-offset-1
    %h1.center_text Editing subcategory
    = render 'form'

app/views/subcategories/index.html.haml
%h1 Listing subcategories

%table
  %tr
    %th Category
    %th Name
    %th
    %th
    %th

  - @subcategories.each do |subcategory|
    %tr
      %td= subcategory.category
      %td= subcategory.name
      %td= link_to 'Show', subcategory
      %td= link_to 'Edit', edit_subcategory_path(subcategory)
      %td= link_to 'Destroy', subcategory, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Subcategory', new_subcategory_path

app/views/subcategories/new.html.haml
.row
  .col-sm-8.col-offset-1
    %h1.center_text New subcategory
    = render 'form'

app/views/subcategories/show.html.haml
.row
  .col-sm-8.col-sm-offset-1
    %h1.inline_block= "#{@subcategory.category} / #{@subcategory.name}"
    - if can? :edit, @subcategory
      = link_to edit_subcategory_path(@subcategory) do
        %i.glyphicon.glyphicon-pencil
    %ul
      - @subcategory.experiences.each do |experience|
        %li
          %h3= link_to experience, experience
      - if can? :create, Experience
        %li
          = link_to new_experience_path, class: 'btn btn-default btn-xs' do 
            %i.glyphicon.glyphicon-plus
            Experience