config/routes.rb
App001::Application.routes.draw do
  resources :evaluations

  root to: "home#index"
  
  get "home/index"
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :experiences do
    collection do 
      get :random
    end
  end
  resources :subcategories
  resources :categories
  resources :password_resets
  resources :users
  resources :sessions

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role? 'admin'
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :subcategories, dependent: :destroy

  def to_s
    name
  end
end

app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
  belongs_to :experience
  belongs_to :user
end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :subcategory
  has_many :evaluations, dependent: :destroy

  def to_s
    title
  end
end

app/models/password_reset.rb
# encoding: utf-8
class PasswordReset < ActiveRecord::Base
  RESET_TIME_VALIDITY = 2.days

  belongs_to :user
  
  validates :user, presence: true
  validates :token, uniqueness: true

  before_create :set_random_token, :set_expires_at
  after_create { PasswordResetMailer.after_create_mailer(self).deliver }

  def self.new_from_email(email)
    user = User.find_by email: email
    PasswordReset.new user: user
  end

  def set_random_token
    begin
      self.token = SecureRandom.urlsafe_base64
    end while PasswordReset.exists?(token: token)
  end

  def set_expires_at
    self.expires_at = DateTime.now + RESET_TIME_VALIDITY
  end

  def can_be_used?
    not expired? and not used
  end

  def expired?
    DateTime.now > expires_at
  end
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  belongs_to :category
  has_many :experiences, dependent: :destroy

  def to_s
    name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :email, presence: true
  validates :email, uniqueness: true
  validates :email, format: {with: VALID_EMAIL_REGEX, message: "Invalid email"}

  before_create { set_unique_random_field_to :authentication_token }
  before_save { self.email.downcase! }

  has_many :password_resets, dependent: :destroy
  has_many :evaluations, dependent: :destroy

  def set_unique_random_field_to(column_name)
    begin
      self[column_name] = SecureRandom.urlsafe_base64
    end while self.class.exists?(column_name => self[column_name])
  end

  def role?(a_role)
    role == a_role
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_login
  def index
    @user = User.new
    render 'index'
  end
end

app/controllers/sessions_controller.rb
# encoding: utf-8
class SessionsController < ApplicationController
  skip_before_action :require_login 

  def new
  end

  def create
    user = User.find_by_email(params[:sessions][:email].downcase)
    if authenticated?(user, params[:sessions][:password]) and user.role != 'visitor' 
      login user
      redirect_to root_path
    else
      redirect_to new_session_path, alert: 'Invalid email or password'
    end
  end

  def destroy
    logout
    redirect_to root_path
  end

  private
    def authenticated?(user, password)
      user && user.authenticate(password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:new, :create]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        make_admin_if_first @user
        login @user
        format.html { redirect_to categories_path, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def make_admin_if_first(user)
    if User.count == 1
      user.update_attribute(:role, 'admin')
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
# encoding: utf-8
module SessionsHelper
  def login(user)
    cookies.permanent[:authentication_token] = user.authentication_token    
  end

  def logout
    cookies.delete :authentication_token
    self.current_user = nil
  end

  def current_user
    @current_user ||= User.find_by_authentication_token cookies[:authentication_token]
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def logged_out?
    !logged_in?
  end

  def require_login
    redirect_to new_session_path, alert: "Login required" if logged_out?
  end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/helpers/subcategory_helper.rb
module SubcategoryHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html{lang: 'en'}
  = render 'shared/head'
  = render 'shared/analytics'
  %body.background_main
    .container_main
      = render 'shared/navigation_bar'
      .container.body
        .row
          .col-md-12
            = render 'shared/alerts'
        = yield
      = render 'shared/footer'

app/views/shared/_alerts.html.haml
- flash.each do |key, value|
  %div{class: "alert alert-#{key} fade in"}
    %button.close{data: {dismiss: "alert"}} &times;
    %strong= value

app/views/shared/_analytics.html.haml
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-31462538-3']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/shared/_footer.html.haml
.footer
  .container

app/views/shared/_head.html.haml
%head
  %title Arquitectura de computadores
  = stylesheet_link_tag "application", media: "all"
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = csrf_meta_tags

app/views/shared/_logged_in_menu.html.haml
%ul.nav.navbar-nav.navbar-right
  %li.dropdown
    = link_to '#', class: 'dropdown-toggle', data: {toggle: 'dropdown'} do
      = current_user.name
      %b.caret
    %ul.dropdown-menu
      %li
        = link_to 'Profile', current_user, onclick: "_gaq.push(['_trackEvent', 'NavBar', 'Profile', 'Click', 1]);"
      %li
        = link_to 'Edit Profile', edit_user_path(current_user)
      %li.divider
      %li
        = link_to logout_path, :method => :delete do
          %i.glyphicon.glyphicon-off

app/views/shared/_logged_out_menu.html.haml
%ul.nav.navbar-nav.navbar-right
  %li= link_to 'Login', new_session_path
  %li= link_to 'Register', new_user_path

app/views/shared/_navigation_bar.html.haml
%nav.navbar.navbar-static-top.navbar-inverse{role: "navigation"}
  .container
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#navbar-collapse-9", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    / Collect the nav links, forms, and other content for toggling
    #navbar-collapse-9.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to root_path do
            %i.glyphicon.glyphicon-home
        - if logged_in?
          %li
            = link_to categories_path do
              %i.glyphicon.glyphicon-list
        - if logged_in?
          %li
            = link_to random_experiences_path do
              %i.glyphicon.glyphicon-random

            
      %nav.collapse.navbar-collapse.bs-navbar-collapse{role: "navigation"}
        - if logged_in?
          = render 'shared/logged_in_menu'
        - else
          = render 'shared/logged_out_menu'