config/routes.rb
App001::Application.routes.draw do
  resources :evaluations

  root to: "home#index"
  
  get "home/index"
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :experiences do
    collection do 
      get :random
    end
  end
  resources :subcategories
  resources :categories
  resources :password_resets
  resources :users
  resources :sessions

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :subcategories, dependent: :destroy

  def to_s
    name
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController  
  before_action :load_category, only: :create
  load_and_authorize_resource

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def load_category
      @category = Category.new(category_params)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= simple_form_for(@category) do |f|
  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit, class: 'btn btn-primary pull-right'
    .clearfix

app/views/categories/edit.html.haml
.row
  .col-sm-8.col-sm-offset-1
    %h1.center_text Editing category
    = render 'form'

app/views/categories/index.html.haml
.row
  .col-sm-12
    %h1 Categories
    %ul
      - @categories.each do |category|
        %li 
          %h3.inline_block= link_to category, category
          - if can? :edit, category
            = link_to edit_category_path(category) do
              %i.glyphicon.glyphicon-pencil
          - if can? :destroy, category
            = link_to category, :method => :delete, :data => { :confirm => 'Are you sure?' } do
              %i.glyphicon.glyphicon-trash
      - if can? :create, Category
        %li
          = link_to '+ Category', new_category_path, class: 'btn btn-default btn-xs'

app/views/categories/new.html.haml
.row
  .col-sm-8.col-sm-offset-1
    %h1.center_text New category
    = render 'form'

app/views/categories/show.html.haml
.row
  .col-sm-8.col-offset-1
    %h1.inline_block
      = @category.name
    - if can? :edit, @category
      = link_to edit_category_path(@category) do
        %i.glyphicon.glyphicon-pencil
    %ul
      - @category.subcategories.each do |subcategory|
        %li
          %h3=link_to subcategory, subcategory
      - if can? :create, Subcategory
        %li
          = link_to '+ Subcategory', new_subcategory_path, class: 'btn btn-default btn-xs'
            